curl -X 'POST' \
  'http://192.168.0.103:5000/api/student/register' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwIiwidXNlcm5hbWUiOiJGSU43OTc2Nzg0Iiwicm9sZSI6ImZpbmFuY2UiLCJpYXQiOjE3MzM1MzU3NDMsImV4cCI6MTczMzUzOTM0M30.xn5PNN26R9bgpUPtDUAiOLYkKgrkAF5FlERyveYZEV8' \
  -H 'Content-Type: multipart/form-data' \
  -F 'firstName=Samson' \
  -F 'lastName=Tesfaye' \
  -F 'dateOfBirth=2024-12-07' \
  -F 'gender=Male' \
  -F 'bloodGroup=A+' \
  -F 'religionStatus=Christian' \
  -F 'emailAddress=sami@gmail.com' \
  -F 'motherTongue=English' \
  -F 'languagesKnown=Amharic, English' \
  -F 'class=11' \
  -F 'section=B' \
  -F 'admissionDate=2024-12-07' \
  -F 'rollNumber=24' \
  -F 'fatherName=Tesfaye' \
  -F 'fatherEmail=tesfaye@gmail.com' \
  -F 'fatherPhone=0911111111' \
  -F 'fatherOccupation=Teacher' \
  -F 'motherName=Lomitu' \
  -F 'motherEmail=lomitu@gmail.com' \
  -F 'motherPhone=0922222222' \
  -F 'motherOccupation=Driver' \
  -F 'parentPassword=@0953714758Ss' \
  -F 'previousSchoolName=Vision Academy' \
  -F 'previousSchoolAddress=Bole, jacros' \
  -F 'password=@0953714758Ss' \
  -F 'guardianType=Legal Guardian' \
  -F 'guardianName=Reta' \
  -F 'guardianRelation=Uncle' \
  -F 'guardianPhone=0933333333' \
  -F 'guardianEmail=reta@gmail.com' \
  -F 'guardianOccupation=Driver' \
  -F 'guardianAddress=Bole, Jacros' \
  -F 'allergies=' \
  -F 'medicalCondition=Good' \
  -F 'medications=' \
  -F 'isSiblingStudyingInSameSchool=No' \
  -F 'siblingName=' \
  -F 'siblingRollNo=' \
  -F 'siblingAdmissionNo=' \
  -F 'siblingClass=' \
  -F 'studentImage=@uploads/photo_2024-11-05_16-30-13.jpg;type=image/jpeg' \
  -F 'documents=@uploads/INSA SERVICES AUTOMATION.pdf;type=application/pdf' \
  -F 'fatherDocument=@uploads/photo_2024-11-03_09-57-10.jpg;type=image/jpeg' \
  -F 'motherDocument=@uploads/photo_2024-11-03_09-57-10.png;type=image/png' \
  -F 'guardianDocument=@uploads/INSA SERVICES AUTOMATION.pdf;type=application/pdf'