# backend/docs/api.docs.yaml

openapi: 3.1.0
info:
  title: School Hub API
  version: 1.0.0
  description: Comprehensive API documentation for SchoolHub platform
  contact:
    name: SchoolHub Development Team
    email: support@schoolhub.edu
servers:
  - url: http://localhost:5000/
    description: Local development server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
        data:
          type: object
security:
  - bearerAuth: []
paths:
  /:
    get:
      tags: [Default]
      summary: Home
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
